services:
  - type: web
    name: institut-francais-madagascar
    runtime: node
    buildCommand: rm -rf node_modules package-lock.json && npm install --production=false && npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_ENV
        value: production